// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // A CLI do Prisma 7 lê a URL por este arquivo, não pelo schema.prisma.
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
